### PR TITLE
Item picker qa issue

### PR DESCRIPTION
**Pull request by briandaviddavidson**
# Item picker issue discovered on QA

## Description
Fixes issue @ghudgins saw in QA with the sidebar by moving the sidebar code out of the item list and placing it above.

image

## New Unit and Integration Tests?
No, this was a style related update. No DOM changed, just structure and minor style tweaks.

## Hub End-to-End Tests Run?
Yes

## Item Picker Screen Caps
If the PR touches the `{{item-picker...` we want some screen caps to show that no visual regression has occured in the three main contexts it is used:

- item picker in normal modal

regular modal

- item picker in full-screen modal
fullscreen

- item picker in god modal

god modal

### CODE REVIEW

**Comment by BRolly8908** [comment]
Product opinion incoming...
Should we have the side panel cover up the search bar?  It feels like the side panel is referencing the selection on the rows and should be top aligned to that area (i.e. bottom of search == top of side panel).  @samanthahunter any thoughts here?

Seems like an easy fix right @briandaviddavidson?

**Comment by briandaviddavidson** [comment]
Yeah, that should be easy to implement. Since it's absolutely positioned, it should be easy to move it down

**Comment by BRolly8908** [comment]
I vote for that, seems to be a better experience for the user 🖖🏻

**Comment by samanthahunter** [comment]
You guys are too fast for me, sorry... @briandaviddavidson @BRolly8908 

This panel was originally meant to be full height (which is why there is a "Back" button inside it... You click a title from the list, the panel opens, and you choose/view it or go "back" to the full table view. Not saying that's how it should work, but that was the pattern we were going for.)

Now that it's changed to not full height... Can we do something like this?
(Or at least can we change the "back" button to "Close" so it makes more sense in context?

38143433-87d77e3c-340e-11e8-9c8f-faadf547f277

**Comment by BRolly8908** [comment]
@briandaviddavidson I vote keep overlap, but switch `Back` UI Button to `Close` UI Button.  Cool @samanthahunter?

**Comment by samanthahunter** [comment]
I'm good with that @BRolly8908 - can we do that @briandaviddavidson

**Comment by briandaviddavidson** [comment]
@mjuniper Yep. That last one is it. Once everything is green, I'll merge

**Pull request merged**
